function [fitresult, gof] = muFitFcn(T, mu)
% -------------------------------------------------------------------------
    %CREATEFIT(T,MU)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input: T
    %      Y Output: mu
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 21-Apr-2023 10:44:34
    
% -------------------------------------------------------------------------
    %% Fit: 'untitled fit 1'.
    [xData, yData] = prepareCurveData( T, mu );
    
    % Set up fittype and options.
    ft = fittype( 'smoothingspline' );
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft );
 % -------------------------------------------------------------------------   
    % Plot fit with data.
    % figure( 'Name', 'untitled fit 1' );
    % h = plot( fitresult, xData, yData );
    % legend( h, 'mu vs. T', 'untitled fit 1', 'Location', 'NorthEast', ...
    %       'Interpreter', 'none' );
    % Label axes
    % xlabel( 'T', 'Interpreter', 'none' );
    % ylabel( 'mu', 'Interpreter', 'none' );
    % grid on
% -------------------------------------------------------------------------
end